name: test_and_deploy

on:
  push:
  workflow_dispatch:
    inputs:
      action:
        description: "Que souhaiter exucuter ?"
        required: false
        default: "deploiment"  
        type: choice
        options:
          - deploiment
          - addition
          - soustraction
          - all_tests 

jobs:
  test_add:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || inputs.action != 'soustraction' 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run test_add
        run: npm run test_add
        
  test_sub:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || inputs.action != 'addition' 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run test_sub
        run: npm run test_sub
  
  deploy:
    runs-on: ubuntu-latest
    needs: [test_add, test_sub]
    if: inputs.action == 'deploiment' || github.event_name == 'push'
    steps:
      - name: Deployment
        run: echo "Déploiement"

  notify_failure:
    runs-on: ubuntu-latest
    needs: [deploy, test_sub, test_add]
    if: failure()
    steps:
      - name: Notify failure
        run: echo "Le déploiement a échoué"
